<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.2.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Notifications.Biz\Notifications.Biz.csproj" />
    <ProjectReference Include="..\Notifications.Biz.Model\Notifications.Biz.Model.csproj" />
    <ProjectReference Include="..\Notifications.Data\Notifications.Data.csproj" />
    <ProjectReference Include="..\Notifications.Data.Model\Notifications.Data.Model.csproj" />
  </ItemGroup>

</Project>
